import type { BlogPost } from "@/types/content";

export const blogCatalog: BlogPost[] = [
  {
    slug: "best-json-formatting-practices",
    title: "Best JSON Formatting Practices for Clean APIs",
    excerpt: "Improve API readability and debugging speed with practical JSON formatting standards.",
    category: "Web Development",
    tags: ["JSON", "API", "Backend"],
    author: "ASVerse Editorial",
    updatedAt: "2026-01-14",
    readingMinutes: 6,
    relatedToolSlugs: ["json-formatter", "json-validator"],
    sections: [
      { id: "why-formatting", heading: "Why formatting matters", content: "Readable JSON reduces mistakes in API collaboration and makes logs easier to scan." },
      { id: "consistent-keys", heading: "Use consistent key naming", content: "Stick to one naming convention like camelCase across responses." },
      { id: "validation", heading: "Validate before shipping", content: "Validate payloads in CI to avoid production parsing errors." },
    ],
    faqs: [
      { question: "Should JSON be minified in production?", answer: "For network transfer, yes. For docs and examples, keep it formatted." },
      { question: "What is the best key naming style?", answer: "Choose one style and apply it consistently across endpoints." },
    ],
  },
  {
    slug: "how-students-can-use-cgpa-calculators",
    title: "How Students Can Use CGPA Calculators Effectively",
    excerpt: "A practical method for tracking semester progress and planning grade improvements.",
    category: "Students",
    tags: ["CGPA", "Students", "Productivity"],
    author: "ASVerse Editorial",
    updatedAt: "2026-01-22",
    readingMinutes: 5,
    relatedToolSlugs: ["cgpa-calculator", "gpa-calculator", "attendance-calculator"],
    sections: [
      { id: "collect-data", heading: "Collect your semester data", content: "Gather grade points and credits from each semester before calculating." },
      { id: "target-goals", heading: "Set target CGPA goals", content: "Use what-if planning to understand how upcoming grades impact your cumulative score." },
      { id: "review-monthly", heading: "Review monthly", content: "Check progress monthly to identify subjects needing extra focus." },
    ],
    faqs: [
      { question: "Does CGPA include all semesters?", answer: "Yes, CGPA is cumulative across all completed semesters." },
      { question: "Can I improve CGPA later?", answer: "Yes, strong performance in later semesters can raise your overall CGPA." },
    ],
  },
  {
    slug: "pomodoro-for-developers",
    title: "Pomodoro for Developers: A Simple Deep-Work Routine",
    excerpt: "Use 25-minute focus sessions to reduce context switching and ship faster.",
    category: "Productivity",
    tags: ["Pomodoro", "Focus", "Developers"],
    author: "ASVerse Editorial",
    updatedAt: "2026-02-02",
    readingMinutes: 4,
    relatedToolSlugs: ["pomodoro-timer", "word-counter"],
    sections: [
      { id: "start-small", heading: "Start with one block", content: "Begin with one 25-minute block and increase gradually." },
      { id: "remove-distractions", heading: "Reduce distractions", content: "Close non-essential tabs and mute notifications before each block." },
      { id: "track-results", heading: "Track outcomes", content: "Log completed blocks daily to measure consistency." },
    ],
    faqs: [
      { question: "Is 25 minutes mandatory?", answer: "No, you can adapt intervals based on task complexity." },
      { question: "How many sessions per day?", answer: "Most people benefit from 4 to 8 focused sessions." },
    ],
  },
  {
    slug: "regex-for-beginners-practical-guide",
    title: "Regex for Beginners: A Practical Cheat-Sheet Guide",
    excerpt: "Understand regex patterns with beginner-friendly examples and testing workflow.",
    category: "Programming",
    tags: ["Regex", "Programming", "Debugging"],
    author: "ASVerse Editorial",
    updatedAt: "2026-02-10",
    readingMinutes: 7,
    relatedToolSlugs: ["regex-tester", "text-diff-checker"],
    sections: [
      { id: "core-syntax", heading: "Core syntax you must know", content: "Start with anchors, quantifiers, groups, and character classes." },
      { id: "test-iteratively", heading: "Test iteratively", content: "Build complex patterns in small steps and validate each part." },
      { id: "avoid-overmatching", heading: "Avoid overmatching", content: "Use boundaries to prevent accidental captures." },
    ],
    faqs: [
      { question: "Is regex hard to learn?", answer: "It becomes manageable with repetitive practice and examples." },
      { question: "Where should I test regex safely?", answer: "Use a dedicated tester with flags and match preview." },
    ],
  },
  {
    slug: "ai-productivity-workflow-for-creators",
    title: "AI Productivity Workflow for Students and Creators",
    excerpt: "A lightweight framework to use AI tools without over-depending on them.",
    category: "Artificial Intelligence",
    tags: ["AI", "Productivity", "Students"],
    author: "ASVerse Editorial",
    updatedAt: "2026-02-15",
    readingMinutes: 6,
    relatedToolSlugs: ["reading-time-calculator", "study-hours-planner"],
    sections: [
      { id: "prompt-template", heading: "Use a prompt template", content: "Define context, output format, and constraints before prompting." },
      { id: "verify-output", heading: "Always verify output", content: "Cross-check facts and code snippets with primary references." },
      { id: "retain-originality", heading: "Retain originality", content: "Use AI for drafting, then rewrite with your own insights." },
    ],
    faqs: [
      { question: "Can AI replace deep study?", answer: "No. It can accelerate learning but cannot replace understanding." },
      { question: "How do I avoid AI hallucinations?", answer: "Ask for sources and validate claims manually." },
    ],
  },
  {
    slug: "cybersecurity-basics-every-intern-should-know",
    title: "Cybersecurity Basics Every Intern Should Know",
    excerpt: "A practical intro to password safety, phishing detection, and secure browsing.",
    category: "Cybersecurity",
    tags: ["Security", "Password", "Phishing"],
    author: "ASVerse Editorial",
    updatedAt: "2026-02-20",
    readingMinutes: 5,
    relatedToolSlugs: ["password-generator", "base64-decoder"],
    sections: [
      { id: "password-hygiene", heading: "Password hygiene", content: "Use unique long passwords and rotate compromised ones quickly." },
      { id: "phishing-signals", heading: "Phishing signals", content: "Check sender domain, urgency language, and suspicious links." },
      { id: "device-practices", heading: "Device practices", content: "Keep OS updated and enable multi-factor authentication." },
    ],
    faqs: [
      { question: "Are password managers safe?", answer: "Yes, reputable managers are safer than reusing weak passwords." },
      { question: "Is public Wi-Fi always risky?", answer: "It can be; avoid sensitive transactions without VPN." },
    ],
  },
  {
    slug: "career-roadmap-for-junior-web-developers",
    title: "Career Roadmap for Junior Web Developers",
    excerpt: "A practical 12-month roadmap to become employable as a frontend/fullstack junior.",
    category: "Careers",
    tags: ["Career", "Web Development", "Learning"],
    author: "ASVerse Editorial",
    updatedAt: "2026-02-25",
    readingMinutes: 8,
    relatedToolSlugs: ["study-hours-planner", "pomodoro-timer"],
    sections: [
      { id: "core-stack", heading: "Master core stack", content: "Prioritize HTML, CSS, JavaScript, TypeScript, and one framework." },
      { id: "project-depth", heading: "Build depth projects", content: "Ship 3 projects with clear README and deployment links." },
      { id: "job-prep", heading: "Prepare for interviews", content: "Practice communication, system basics, and debugging." },
    ],
    faqs: [
      { question: "Do I need a CS degree?", answer: "Not always; strong projects and consistency can be enough." },
      { question: "What matters most in portfolio?", answer: "Clarity, code quality, and real problem-solving." },
    ],
  },
  {
    slug: "seo-meta-tags-that-actually-matter",
    title: "SEO Meta Tags That Actually Matter in 2026",
    excerpt: "Focus on the small set of metadata fields that move rankings and CTR.",
    category: "SEO",
    tags: ["SEO", "Meta Tags", "Technical SEO"],
    author: "ASVerse Editorial",
    updatedAt: "2026-03-01",
    readingMinutes: 6,
    relatedToolSlugs: ["meta-tag-generator", "slug-generator", "robots-txt-generator"],
    sections: [
      { id: "titles", heading: "Title and description", content: "Write clear intent-matching titles and concise meta descriptions." },
      { id: "canonical", heading: "Canonical and indexing", content: "Use canonical URLs to avoid duplicate-content confusion." },
      { id: "social-cards", heading: "Social cards", content: "Set OG/Twitter tags to improve share previews and CTR." },
    ],
    faqs: [
      { question: "Do meta keywords help?", answer: "No, modern search engines mostly ignore them." },
      { question: "Should every page have unique metadata?", answer: "Yes, uniqueness improves relevance and click-through rate." },
    ],
  },
  {
    slug: "beginner-guide-to-emi-and-loan-planning",
    title: "Beginner Guide to EMI and Loan Planning",
    excerpt: "Understand EMI components before taking personal, education, or home loans.",
    category: "Finance",
    tags: ["Finance", "EMI", "Loans"],
    author: "ASVerse Editorial",
    updatedAt: "2026-03-05",
    readingMinutes: 5,
    relatedToolSlugs: ["emi-calculator", "simple-interest-calculator", "compound-interest-calculator"],
    sections: [
      { id: "emi-basics", heading: "EMI basics", content: "EMI includes principal and interest with tenure-based spread." },
      { id: "interest-impact", heading: "Interest rate impact", content: "Small rate changes significantly affect total repayment." },
      { id: "prepayment", heading: "Prepayment strategy", content: "Early partial prepayment can reduce long-term burden." },
    ],
    faqs: [
      { question: "Is longer tenure always better?", answer: "It reduces EMI but can increase total interest paid." },
      { question: "How much EMI is safe?", answer: "Many planners suggest staying below 30-40% of monthly income." },
    ],
  },
  {
    slug: "best-practices-for-image-optimization-web",
    title: "Best Practices for Web Image Optimization",
    excerpt: "Reduce page load time with practical image conversion and compression tips.",
    category: "Web Development",
    tags: ["Images", "Performance", "Core Web Vitals"],
    author: "ASVerse Editorial",
    updatedAt: "2026-03-10",
    readingMinutes: 6,
    relatedToolSlugs: ["image-compressor", "image-to-webp", "dominant-color-extractor"],
    sections: [
      { id: "right-format", heading: "Choose the right format", content: "Use WebP/AVIF for most photos and PNG for transparency-heavy assets." },
      { id: "responsive-images", heading: "Serve responsive images", content: "Deliver multiple sizes based on device width." },
      { id: "optimize-pipeline", heading: "Automate optimization", content: "Use build-time compression and lazy loading." },
    ],
    faqs: [
      { question: "Should I convert all images to WebP?", answer: "Mostly yes, but verify quality and browser fallback needs." },
      { question: "Do big images affect SEO?", answer: "Yes, slower pages can reduce user engagement and rankings." },
    ],
  },
  {
    slug: "technical-writing-checklist-for-developers",
    title: "Technical Writing Checklist for Developers",
    excerpt: "Write clearer docs and tutorials using a reusable structure template.",
    category: "Programming",
    tags: ["Documentation", "Writing", "Developers"],
    author: "ASVerse Editorial",
    updatedAt: "2026-03-15",
    readingMinutes: 5,
    relatedToolSlugs: ["word-counter", "reading-time-calculator", "text-case-converter"],
    sections: [
      { id: "audience", heading: "Define audience first", content: "Choose beginner, intermediate, or advanced before drafting." },
      { id: "examples", heading: "Use executable examples", content: "Readers trust docs with working commands and clear outcomes." },
      { id: "structure", heading: "Use skimmable structure", content: "Short paragraphs, bullets, and heading hierarchy increase readability." },
    ],
    faqs: [
      { question: "How long should docs be?", answer: "As long as needed to remove ambiguity, but no longer." },
      { question: "Should I include troubleshooting?", answer: "Yes, it greatly improves practical usefulness." },
    ],
  },
];

export function getPostBySlug(slug: string) {
  return blogCatalog.find((post) => post.slug === slug);
}

export const blogCategories = Array.from(new Set(blogCatalog.map((post) => post.category)));
export const blogTags = Array.from(new Set(blogCatalog.flatMap((post) => post.tags)));
